- name: Provision zookeeper environment
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    project_name: "zookeeper_firehose"

  vars_files:
    - vars/aws/zookeeper.yaml
    - vars/aws/aws.yaml

  tasks:
    - include: tasks/aws/keypair.yaml
    - include: tasks/aws/securitygroup.yaml
    - include: tasks/aws/instances.yaml