---
- name: Generate aws vars file
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    project_name: "zookeeper_firehose"

  vars_files:
    - vars/aws/zookeeper.yaml

  roles:
    - name: community/aws_config