---
- name: Generate deploy vars file
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    project_name: "zookeeper_firehose"

  vars_files:
    - vars/aws/zookeeper.yaml
    - vars/deploy/zookeeper.yaml
    - vars/aws/aws.yaml

  roles:
    - name: community/deploy_config